# Generated by Django 4.2.16 on 2026-04-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system', models.CharField(choices=[('marks', 'Marks'), ('gpa', 'GPA'), ('cce', 'CCE'), ('cwa', 'CWA'), ('custom', 'Custom')], default='marks', max_length=20)),
                ('auto_unique_ids', models.BooleanField(default=True)),
                ('unique_id_prefix', models.CharField(blank=True, max_length=20)),
                ('unique_id_padding', models.PositiveSmallIntegerField(default=4)),
                ('default_country', models.CharField(blank=True, max_length=100)),
                ('default_currency', models.CharField(blank=True, max_length=10)),
                ('default_time_zone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('default_language', models.CharField(blank=True, default='en', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
